---
- hosts: localhost
  become: yes
  tasks:
    - name: Install Packages
      apt: 
        name: openjdk-8-jdk
        state: present
      become: yes
            
    - name: Update apt cache
      apt:
        update_cache: yes
      become: yes

    - name: Install Node.js and npm
      apt:
        name: "{{ item }}"
        state: present
      become: yes
      loop:
        - nodejs
        - npm

    - name: Clone the Git repository
      git:
        repo: "https://github.com/pnp2484/node_express_github_actions"
        dest: "/opt/your_app"
        version: "main"
      become: yes

    - name: Install project dependencies
      command: npm install
      args:
        chdir: /opt/your_app

    - name: Execute Date Command
      command: date
    
    - name: Execute java version check
      command: java -version
    
    - name: Test local action
      command: echo "Hello World"